create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


create table public.tasks (
    id bigint generated by default as identity primary key,

    slug text not null unique,
    title text not null,
    description text,

    task_type text not null,

    fixed_date date,

    config jsonb not null default '{}'::jsonb,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


create table public.user_tasks (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    task_id bigint not null
        references public.tasks(id)
        on delete cascade,

    position integer not null,

    available_date date not null,

    created_at timestamptz not null default now(),

    constraint user_tasks_unique_task
        unique (user_id, task_id),

    constraint user_tasks_unique_position
        unique (user_id, position),

    constraint user_tasks_position_range
        check (position between 1 and 25)
);


create table public.task_responses (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    task_id bigint not null
        references public.tasks(id)
        on delete cascade,

    response jsonb not null default '{}'::jsonb,

    completed_at timestamptz,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint task_responses_unique
        unique (user_id, task_id)
);


create index idx_user_tasks_user_id
    on public.user_tasks(user_id);

create index idx_user_tasks_available_date
    on public.user_tasks(available_date);

create index idx_task_responses_user_id
    on public.task_responses(user_id);

create index idx_task_responses_task_id
    on public.task_responses(task_id);

create index idx_tasks_fixed_date
    on public.tasks(fixed_date);