insert into public.tasks (
    slug,
    title,
    description,
    task_type,
    fixed_date,
    config,
    is_active
)
values
('task-01', 'Задание 1', 'Тестовое задание 1', 'content', '2026-12-01', '{}'::jsonb, true),
('task-02', 'Задание 2', 'Тестовое задание 2', 'input', null, '{}'::jsonb, true),
('task-03', 'Задание 3', 'Тестовое задание 3', 'text', null, '{}'::jsonb, true),
('task-04', 'Задание 4', 'Тестовое задание 4', 'crossword', null, '{}'::jsonb, true),
('task-05', 'Задание 5', 'Тестовое задание 5', 'cards', null, '{}'::jsonb, true),
('task-06', 'Задание 6', 'Тестовое задание 6', 'content', null, '{}'::jsonb, true),
('task-07', 'Задание 7', 'Тестовое задание 7', 'quiz', null, '{}'::jsonb, true),
('task-08', 'Задание 8', 'Тестовое задание 8', 'text', null, '{}'::jsonb, true),
('task-09', 'Задание 9', 'Тестовое задание 9', 'image_click', null, '{}'::jsonb, true),
('task-10', 'Задание 10', 'Тестовое задание 10', 'external_link', null, '{}'::jsonb, true),
('task-11', 'Задание 11', 'Тестовое задание 11', 'content', null, '{}'::jsonb, true),
('task-12', 'Задание 12', 'Тестовое задание 12', 'quiz', null, '{}'::jsonb, true),
('task-13', 'Задание 13', 'Тестовое задание 13', 'text', null, '{}'::jsonb, true),
('task-14', 'Задание 14', 'Тестовое задание 14', 'content', '2026-12-14', '{}'::jsonb, true),
('task-15', 'Задание 15', 'Тестовое задание 15', 'cards', null, '{}'::jsonb, true),
('task-16', 'Задание 16', 'Тестовое задание 16', 'input', null, '{}'::jsonb, true),
('task-17', 'Задание 17', 'Тестовое задание 17', 'video', null, '{}'::jsonb, true),
('task-18', 'Задание 18', 'Тестовое задание 18', 'content', null, '{}'::jsonb, true),
('task-19', 'Задание 19', 'Тестовое задание 19', 'quiz', null, '{}'::jsonb, true),
('task-20', 'Задание 20', 'Тестовое задание 20', 'text', null, '{}'::jsonb, true),
('task-21', 'Задание 21', 'Тестовое задание 21', 'email', null, '{}'::jsonb, true),
('task-22', 'Задание 22', 'Тестовое задание 22', 'content', null, '{}'::jsonb, true),
('task-23', 'Задание 23', 'Тестовое задание 23', 'file_upload', null, '{}'::jsonb, true),
('task-24', 'Задание 24', 'Тестовое задание 24', 'future_email', null, '{}'::jsonb, true),
('task-25', 'Задание 25', 'Тестовое задание 25', 'content', '2026-12-25', '{}'::jsonb, true);